Repository kraulain/rbclean-infra, pull requests merged in 2024-08, with the labels that each got.

#9 Project Setup for team
  .gitignore
  README.md
  api-spec/rbclean.yaml
  package.json
Labels: dev-ops 😎 🚀

#15 udated Reame
  README.md
Labels: documentation, dev-ops 😎 🚀

#14 Feature/reports
  api-spec/rbclean.yaml
Labels: report-service

#12 specification-order-management-apis
  .gitignore
  .vscode/settings.json
  api-spec/rbclean.yaml
Labels: order-service
